// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvztitlbouxpbrplowut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2enRpdGxib3V4cGJycGxvd3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Mjk2MzAsImV4cCI6MjA2NzMwNTYzMH0.kgrYVLXeZB0cVRbLKcPVkgHg8CyIz33hcRwc9cn760I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});